"use client";

import { useEffect, useMemo, useState } from "react";

import { Pagination, SearchBox } from "@/components/table-tools";

type Consent = { id: string; user_id: string; client_id: string; client_name: string | null; scopes: string[]; createdAt: string };

export default function ConsentsPage() {
  const [consents, setConsents] = useState<Consent[]>([]); const [pending, setPending] = useState(true); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const [page, setPage] = useState(1);
  useEffect(() => { const timer = window.setTimeout(() => { void fetch("/api/control/consents", { cache: "no-store" }).then(async (response) => { const body = await response.json() as { data?: Consent[]; message?: string }; if (!response.ok) throw new Error(body.message ?? "Consents could not be loaded."); setConsents(body.data ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Consents could not be loaded.")).finally(() => setPending(false)); }, 0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return term ? consents.filter((item) => `${item.client_name ?? ""} ${item.client_id} ${item.user_id} ${item.scopes.join(" ")}`.toLowerCase().includes(term)) : consents; }, [consents, query]); const pages = Math.max(1, Math.ceil(filtered.length / 10)); const visible = filtered.slice((page - 1) * 10, page * 10);
  return <><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-emerald-700">Consent</p><h1 className="mt-1.5 text-xl font-normal tracking-tight">Granted application consent</h1><p className="mt-1.5 text-sm text-slate-500">OAuth consent records currently stored by Better Auth.</p><section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-4 py-3"><p className="text-xs font-medium text-slate-600">{pending ? "Loading consent records…" : `${filtered.length} grants`}</p><SearchBox onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Search consent" value={query} /></div>{!pending && filtered.length === 0 && <div className="grid place-items-center px-6 py-12 text-center"><div aria-hidden="true" className="mb-4 grid size-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><svg className="size-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M6 4h12v16H6zM9 8h6M9 12h6M9 16h4" /></svg></div><p className="text-sm font-medium text-slate-700">{query ? "No matching grants" : "No consent grants yet"}</p></div>}{visible.map((consent) => <div className="border-b border-slate-100 px-4 py-3 last:border-0" key={consent.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-slate-800">{consent.client_name ?? "Unnamed application"}</p><p className="mt-0.5 break-all text-xs text-slate-500">User {consent.user_id} · Client {consent.client_id}</p></div><p className="text-[11px] text-slate-400">{new Date(consent.createdAt).toLocaleString()}</p></div><div className="mt-2 flex flex-wrap gap-1.5">{consent.scopes.map((scope) => <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-600" key={scope}>{scope}</span>)}</div></div>)}<Pagination onChange={setPage} page={page} pages={pages} /></section>{error && <p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700" role="alert">{error}</p>}</>;
}
