apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replicas.yaml
images:
  - name: nova-pos/api
    newTag: dev
  - name: nova-pos/web
    newTag: dev

