"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { authClient } from "@/lib/auth-client";

export default function AdminPage() {
  const [counts, setCounts] = useState<{ people: number | null; applications: number | null }>({ people: null, applications: null });
  useEffect(() => { const timer = window.setTimeout(() => { void Promise.all([authClient.admin.listUsers({ query: { limit: 100, offset: 0 } }), authClient.oauth2.getClients()]).then(([users, clients]) => setCounts({ people: users.error ? null : users.data?.users.length ?? 0, applications: clients.error ? null : clients.data?.length ?? 0 })).catch(() => undefined); }, 0); return () => window.clearTimeout(timer); }, []);
  return <><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-emerald-700">Overview</p><h1 className="mt-1.5 text-xl font-normal tracking-tight">Authentication at a glance</h1><p className="mt-1.5 text-sm text-slate-500">Manage real users, organizations, sessions, and connected applications.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Link className="group rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-px hover:border-emerald-200 hover:shadow-md" href="/admin/users"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><p className="text-sm font-medium">People and access</p><span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-medium text-emerald-700">{counts.people ?? "—"}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">Create users, review status, and manage platform roles.</p><p className="mt-3 text-[11px] text-emerald-700">View people →</p></div><img alt="Connected people" className="h-28 w-28 object-contain transition-transform duration-200 group-hover:scale-105" src="/connected-people.svg" /></div></Link><Link className="group rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-px hover:border-emerald-200 hover:shadow-md" href="/admin/apps"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><p className="text-sm font-medium">Connected applications</p><span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-medium text-emerald-700">{counts.applications ?? "—"}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">Register OAuth clients and control redirect destinations.</p><p className="mt-3 text-[11px] text-emerald-700">View applications →</p></div><img alt="Connected application" className="h-28 w-28 object-contain transition-transform duration-200 group-hover:scale-105" src="/connected-application.svg" /></div></Link></div></>;
}
